### ISSUE TITLE
can philr be used for relative abundance data?

### ISSUE THREAD

**Issue by Jigyasa3** [jsilve24/philr#11]
Hey all

I was wondering if its possible to use philr on proportions data, not represented by composition?
For example, I have shotgun metagenome data of relative abundance of bacterial functions across host tree. 
#table is arranged as following-
Bacteria1 proportion(KEGG_function1)
Bacteria2 proportion(KEGG_function1)
Bacterial3 proportion(KEGG_function1)

The proportions are phylogenetically related but do not correspond to actual bacterial composition.

**Comment by jsilve24** [comment]
So the proportions sum to a constant value (e.g., proportions sum to 1 across the different bacteria)?


If so, yes absolutely this is a good use of philr. 

Justin

**Comment by Jigyasa3** [comment]
@jsilve24 , thanks for replying. My data does sum up to a constant. I wanted to ask another conceptual question regarding the use of the software.

1. According to the paper, philr package transforms the data using the bacterial phylogenetic tree. Is it conceptually feasible to transform the data based on the host phylogenetic tree?
My aim is to analyze if the relative abundance of microbial functions (regardless of microbial taxonomy) is dependent on host phylogeny.

Is it feasible to analyze such data using philr package? I didn't see any mention of host tree in the paper, just host samples which are used for grouping...

**Comment by jsilve24** [comment]
Just to confirm you are saying that the relationship between your samples has some phylogenic structure. Correct?

If that is the case then I don't think PhILR is the appropriate software package for you. PhILR is for when there is phylogenetic structure within the categories / parts / taxa measured in each sample. If you have structure across the samples then you would likely want to look at other methods such as Linear mixed models (of which phylogenic models are a special case). I have a different software package called "stray" github.com/jsilve24/stray which can do these types of things. Look at either the function pibble or the function maltipoo. That said, stray is a little more complicated to use than PhILR as it incorporates aspects of compositional data analysis and bayesian statistics. I would be happy to discuss more in that Repo if you are interested. 

Justin

**Comment by Jigyasa3** [comment]
Thank you so much for your advice! I will try the "stray" package and will ask if I have doubts!

**Comment by manuelzc** [comment]
Hi,

My congratulations and thanks for developing PHILR. I have a question that I think is related to this issue. I am using zcompositions to replace zeros in a microbiome dataset using the cmultRepl function of that package. This operation replaces the raw read counts by relative abundance data. My question is if it is appropriate to use this output as input for philr. I understand that philr will convert the data to relative abundance so I do not know if only raw read counts should be used.

Manolo

**Comment by jsilve24** [comment]
No problem here. It is appropriate to do as you are suggesting. 

Best, 
Justin

**Comment by manuelzc** [comment]
Thank you very much for clarifying this point to me!

Manolo
