### ISSUE TITLE
 l1  Penalty (From the Tutorial)

### ISSUE THREAD

**Issue by biggs-biggsby** [jsilve24/philr#12]
Quick question from the tutorial - "We will use a hard-threshold for the l1 penalty of λ=0.2526 which we choose so that the resulting number of non-zero coefficients is ≈5." Could you please explain the consequences of setting the threshold higher or lower? 

Thanks so much! Have loved using this package.

**Comment by jsilve24** [comment]
Increasing λ will decrease the number of non-zero coefficients decreasing will increase the number. λ is the penalization parameter -- more penalty -> more sparsity. In general this can be set by cross-validation if you re interested purely in maximizing predictive ability. More generally this is a difficult topic where there is often not a clearly right answer.
