### ISSUE TITLE
Interpretation of balance value sign/relative value

### ISSUE THREAD

**Issue by Phylloxera** [jsilve24/philr#14]
![n3](https://user-images.githubusercontent.com/13121075/110386979-9dd49780-8026-11eb-9225-af61925d9b2c.png)
Going through the paper and the tutorial and then applying to some of our datasets, I was interpreting the above graph to mean that the n3(-) clade is associated with the factor 'High' Feed Efficiency while the n3(+) clade is associated with 'Low' Feed Efficiency. My thinking here was the +/- sign of the balance value was instructive. But in this figure, n332 has a median balance value of +/+ for both factors. In this case, do we use the relative values such that the n332(+) clade is associated with 'Less' ADG while n332(-) is associated with 'Greater' ADG?
![n332](https://user-images.githubusercontent.com/13121075/110388293-77176080-8028-11eb-9a86-e0ad71c34115.png)
 Sorry, not really an 'issue' per se. Just confused-at-best or way-off-base-at-worst.

**Comment by jsilve24** [comment]
Sorry for the delay, 

In the first graph, assuming for rhetorical purposes that effect is real: This implies that when the ratio of geometric means of the n3(+) clade over the n3(-) clade increases with the low feed efficiency and is decreased (comparatively) in this high feed efficiency group. 

Does that make sense?

**Comment by jsilve24** [comment]
closing as issue seems to be resolved.
