### ISSUE TITLE
Support for TreeSummarizedExperiment?

### ISSUE THREAD

**Issue by antagomir** [jsilve24/philr#16]
We and others have proposed to complement the capabilities of `phyloseq` based on the new R/Bioc class TreeSummarizedExperiment ([Huang et al. 2020](https://f1000research.com/articles/9-1246)). There is a set of R packages that are emerging around this under the name [miaverse](http://microbiome.github.io/) (European Bioconductor meeting Dec 2020), and in addition the [curatedMetagenomicData](https://waldronlab.io/curatedMetagenomicData/articles/curatedMetagenomicData.html) has started to support this format. 

Adding `philr` support for this format would be great. Ideally, it could be provided in the philr package itself.

The `philr` function operates on OTU table and tree information directly.

How about adding support for `TreeSummarizedExperiment` class in the philr function, or possibly a separate wrapper function that extracts the relevant fields from TreeSE object and then calls philr. 

We could make a PR on this if it fits the philr package.

**Comment by jsilve24** [comment]
I think what would work best is if we turned philr into an s3 method based on the argument `df`. If df is a data.frame its the same method as before, if df is a treesummarisedexperiment or whatever it calls the wrapper.

df is not the best argument name but honestly thats not that important.

How does that sound?

Could you try implementing this? Or at least implementing a wrapper for philr that I could then take and manipulate to this form?

**Comment by antagomir** [comment]
Sounds good. I started looking into this but it turned out that we need to update some other functions in order to do this. The S3 support is now implemented but will need to finalize. I aim to open a PR soon.

**Comment by jsilve24** [comment]
Sounds good, no rush obviously, I just heard about this so take all the time in the world :)

**Comment by antagomir** [comment]
Ok the PR #17 is now ready.

**Comment by jsilve24** [comment]
Closed with #17
