### ISSUE TITLE
Discrepancy in first argument of `philr()`

### ISSUE THREAD

**Issue by mmp3** [jsilve24/philr#19]
The [reference document](https://bioconductor.org/packages/release/bioc/manuals/philr/man/philr.pdf) for the [current release of `philr` on bioconductor](https://bioconductor.org/packages/release/bioc/html/philr.html) states that the first argument to `philr::philr()` is `df`.

However, when installed, the first argument of `philr::philr()` is `x` and there is no `df` argument, in agreement with the Github version.

**Comment by jsilve24** [comment]
Please use the development branch. Odd that that change got pushed to release, I just checked it is correct on the development branch. 

Or install with:

devtools::install_github("jsilve24/philr")

closed
