### ISSUE TITLE
Adding pseudocount option to philr function?

### ISSUE THREAD

**Issue by antagomir** [jsilve24/philr#20]
The philr transformation benefits from pseudocounts. In the current implementation these need to be added before applying this transformation. This requires additional manipulation steps for the data object (matrix, phyloseq, TreeSummarizedExperiment). Hence it would be convenient for the user if the pseudocount could be provided as a function argument to `philr` instead.

I can prepare a PR if this gets support.

At the same go, it could be possible to complement the documentation. The philr manpage currently lists only matrix as the input to philr, although the function supports also other formats (phyloseq, TreeSE).

```
#' @param x \strong{matrix} of data to be transformed (samples are rows,
#' compositional parts are columns) - zero must be dealt with either with
#' pseudocount, multiplicative replacement, or another method. 
```

**Comment by jsilve24** [comment]
I just implemented the pseudocount feature in a new branch. Let me know if that was not what you had in mind. 

Also, feel free to submit a pull request to that branch (the `adding-pseudocount` branch) with updated documentation.

**Comment by antagomir** [comment]
Yes, looks good and seems to work well.
