### ISSUE TITLE
Problems with part.weights='anorm.x.gm.counts'

### ISSUE THREAD

**Issue by FelipeMSD** [jsilve24/philr#25]
Dear all,

When I try to run philr with the Aitchison option:

` gp.philr <- philr(matrix, tree, 
                       part.weights='anorm.x.gm.counts', 
                       ilr.weights='blw.sqrt')`

I have the error: Error in rep(1, nrow(x)) : invalid 'times' argument

However, the same doesn't happen when I try the Euclidean option:

` gp.philr <- philr(matrix, tree, 
                       part.weights='enorm.x.gm.counts', 
                       ilr.weights='blw.sqrt')`

Do you know what might be happening and how to fix it?

Kind regards,
Felipe

**Comment by jsilve24** [comment]
Thanks for pointing this out. Turns out its an error introduced in 8687eff. Fixing now.

**Comment by FelipeMSD** [comment]
Thank you very much! Let me know when I can update it and try again.

**Comment by jsilve24** [comment]
Try:
```
devtools::install_github("jsilve24/philr", branch="fix_post_df_to_x")
```
Please let me know if that fixes your problems or not.

**Comment by FelipeMSD** [comment]
I have this warning message when I try to install this way:

`Warning message:
In devtools::install_github("jsilve24/philr", branch = "fix_post_df_to_x",  :
  Arguments in `...` must be used.
✖ Problematic argument:
• branch = "fix_post_df_to_x"`

Then I try to load it again and run the command line but keep having the same problems... It doesn't seem to be updated...

**Comment by FelipeMSD** [comment]
I tried to use `remotes::install_github(repo='jsilve24/philr', ref = 'fix_post_df_to_x', force = TRUE)` and it seems to be updated now but the error persists...

**Comment by jsilve24** [comment]
Try again. Stupid documentation error.

**Comment by FelipeMSD** [comment]
Nothing changed. Same warning messages and same error.

**Comment by jsilve24** [comment]
Sorry that was just dumb, there doesn't seem to be anything wrong with the package just the install command its `ref` not `branch`. This should work:

```
devtools::install_github("jsilve24/philr", ref="fix_post_df_to_x", force=TRUE)
```

**Comment by FelipeMSD** [comment]
I’m sorry… I on’t know if this might be a problem from my side but even after reinstalling with this command line the error message persists:


Error in rep(1, nrow(x)) : invalid 'times' argument

It’s weird because it only happens with part.weights=‘anorm.x.gm.counts’ but not with part.weights=‘enorm.x.gm.counts’...

Kind regards,
Felipe

On 10 Mar 2023, at 22:35, Justin Silverman ***@***.******@***.***>> wrote:


devtools::install_github("jsilve24/philr", ref="fix_post_df_to_x", force=TRUE)

**Comment by FelipeMSD** [comment]
Somehow it worked now when I tried `remotes::install_github(repo="jsilve24/philr", ref="fix_post_df_to_x", force=TRUE)` again. Thank you very much!
