### ISSUE TITLE
ggtree citation

### ISSUE THREAD

**Issue by GuangchuangYu** [jsilve24/philr#3]
Can you kindly add the `ggtree` citation in the vignette?

<http://dx.doi.org/10.1111/2041-210X.12628>

Thanks.

**Comment by jsilve24** [comment]
Gladly! 16cf23ee4ecd6d26107d5c63ac5e471d54c4133c
I also cited in documentation of annotate_balance function.

**Comment by GuangchuangYu** [comment]
thanks.
