### ISSUE TITLE
Covariate names of the Transform Data using PhILR

### ISSUE THREAD

**Issue by naarkhoo** [jsilve24/philr#4]
If the abundance table is n * m, where n is the number of samples and m is the number of taxa, I noticed the transformed data is n * (m-1); 

From the colnames, I could not find out which taxa is missing because, the final matrix is labeled based on internal nodes (n_1 .... n_m).

I was wondering if you could help me relabeling the covariate names of the transposed abundance table, to the original abundance table.

**Comment by jsilve24** [comment]
The point of the transform is to move from a space defined by the original taxa names (e.g., the m colnames) to a new space defined by m-1 "balances". Specifically each balance is associated with a single internal node of the phylogenetic tree and represents the ratio of relative abundances between the two subclades of a given internal node. More details can be found in our paper which is available at https://elifesciences.org/content/6/e21887. 

It is not that any taxa is "missing" is it that we have transformed the data to now be interms of m-1 "balances". 

You can visualize the relationship between the m-1 balances and the m taxa by plotting the phylogenetic tree with the tip and node names.

This can be done in a few ways. To visualize all at once you can use the following code snippet which uses the ggtree package. 

    library(ggtree)
    plot_tree_and_labels <- function(tree){
      ggtree(tree)+
        geom_tiplab()+
        geom_text2(aes(subset=!isTip, label=label))
    }

In addition as discussed in [the associated vignette](https://bioconductor.org/packages/release/bioc/vignettes/philr/inst/doc/philr-intro.html) we have written a few functions like `name.balance` or `annotate_balance` which are intended to help users visualize and identify what balances are associated with which taxa. 

I hope this helps!
